### ISSUE TITLE
david, met zoveel issues kan ik toch niet werken jonge

### ISSUE THREAD

**Issue by AtzeDeVries** [naturalis/stargazer#10]

**Comment by import-naturalis** [comment]
or mute the thread
<https://github.com/notifications/unsubscribe/AI-4d8AvTpZH676dF92wa2OpAmC3A6zsks5qSQNsgaJpZM4JEWSj>
.

On 4 July 2016 at 14:58, Atze de Vries <notifications@github.com> wrote:

> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/naturalis/stargazer/issues/10>, or mute the thread
> <https://github.com/notifications/unsubscribe/AI-4d8AvTpZH676dF92wa2OpAmC3A6zsks5qSQNsgaJpZM4JEWSj>
> .
>



-- 

Met vriendelijke groet,

David Heijkamp
Senior projectleider


M 06 4177 4866
Vondellaan 55, Postbus 9517, 2300 RA Leiden
E david.heijkamp@naturalis.nl, I www.naturalis.nl

Onze huidige tentoonstelling is geopend tot 31 augustus 2016. Vanaf 10
september verwelkomen we ons publiek bij de tentoonstelling T.rex in Town
in het huidige entreegebouw.

Ondertussen bouwen we een vernieuwd museum dat eind 2018 open gaat.
