### ISSUE TITLE
Hip projectname

### ISSUE THREAD

**Issue by davidheijkamp** [naturalis/stargazer#2]
As a developer, I want to have a nice, hip, sexy name for the project so that I can attract more colleagues from other museums in the rest of the world.

**Comment by wilfredgerritsen** [comment]
😁 goed idee

On 30 June 2016 at 11:38, David Heijkamp <notifications@github.com> wrote:

> As a developer, I want to have a nice, hip, sexy name for the project so
> that I can attract more colleagues from other museums in the rest of the
> world.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/naturalis/museumonoff/issues/2>, or mute the thread
> <https://github.com/notifications/unsubscribe/AHbsER5sJGo00Rums4iSsXo4FNGWoZbNks5qQ46agaJpZM4JB-jA>
> .
>



-- 
Met vriendelijke groet,

Wilfred Gerritsen
Informatie analist

T 071-7519349
Vondellaan 55. Leiden

E Wilfred.Gerritsen@naturalis.nl I , www.naturalis.nl

**Comment by AtzeDeVries** [comment]
http://www.chesapeakebay.net/fieldguide/critter/northern_stargazer

Stargazer?

**Comment by davidheijkamp** [comment]
There are a couple of projects on Github named stargazer. Nothing related to the project we're doing. Renamed the project to stargazer.
